function PlotData(x,y)
hfig = findall(0,'Type','figure','tag','FigureStateSpace'); 
hax = findall(hfig,'Type','Axes','tag','StateSpaceAxes'); 
hold(hax,'on');
axis(hax,'auto');
scatter(x,y,...
    100,'filled',...
    'MarkerFaceColor',[0.8 0 0],...
    'MarkerFaceAlpha',0.5,...
    'Parent',hax);
end