using System;
using System.Collections.Generic;
using System.Text;
using MathWorks.MATLAB.NET.Arrays;
using MathWorks.MATLAB.NET.Utility;
using PlotStateSpaceComp;

/// <summary>
/// Sample driver code that integrates a compiled MATLAB function
/// generated by MATLAB Compiler SDK
///
/// Refer to the MATLAB Compiler SDK documentation for more
/// information.
/// </summary>
class plot_state_spaceSample1 {

	static Class1 class1Instance;

	static void Setup() {
		class1Instance = new Class1();
	}

	/// <summary>
	/// Example of using the plot_state_space function.
	/// </summary>
	public static void Plot_state_spaceSample() {
		double xInData = 0.0;
		double yInData = 0.0;
		Object[] results = null;
		try {
			MWNumericArray xIn = new MWNumericArray(xInData);
			MWNumericArray yIn = new MWNumericArray(yInData);
			results = class1Instance.plot_state_space(xIn, yIn);
		} catch (Exception e) {
			Console.WriteLine(e);
		}
	}

	/// <summary>
	/// The main entry point for the application.
	/// </summary>
	static void Main(string[] args) {
		try {
			Setup();
		} catch (Exception e) {
			Console.WriteLine(e);
			Environment.Exit(1);
		}
		try {
			Plot_state_spaceSample();
		} catch (Exception e) {
			Console.WriteLine(e);
			Environment.Exit(1);
		}
	}

}
